# Generated by Django 3.2.7 on 2021-09-16 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210916_0730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addon',
            options={'verbose_name': 'Аддон', 'verbose_name_plural': 'Аддоны'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
