# Generated by Django 3.2.7 on 2021-09-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210916_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_vegan',
            field=models.BooleanField(default=False, verbose_name='Вегатарианская'),
        ),
    ]
