# Generated by Django 3.2.7 on 2021-09-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_category_is_vegan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_vegan',
            field=models.BooleanField(default=False, verbose_name='Вегетарианская'),
        ),
    ]
