# Generated by Django 3.2.7 on 2021-09-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20210916_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='addon',
            field=models.ManyToManyField(to='catalog.Product'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=16, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Наименование'),
        ),
    ]
