# Generated by Django 3.2.7 on 2021-09-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20210916_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=32, verbose_name='Наименование'), max_length=256),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=16, unique=True, verbose_name='Наименование'), max_length=256, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=32, unique=True, verbose_name='Наименование'), max_length=256),
        ),
    ]
