# Generated by Django 3.2.7 on 2021-09-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20210917_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='slug',
            field=models.SlugField(default='0', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_vegan',
            field=models.BooleanField(default=' 0 ', verbose_name='Вегетарианская'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=' 0 ', max_length=256, null=True),
        ),
    ]
