# Generated by Django 3.2.7 on 2021-09-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20210917_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='slug',
            field=models.SlugField(default=2, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_vegan',
            field=models.BooleanField(default=2, verbose_name='Вегетарианская'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=2, max_length=256, null=True),
        ),
    ]
