# Generated by Django 3.2.7 on 2021-09-17 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20210917_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addon',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
