# Generated by Django 3.2.7 on 2021-09-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20210917_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_vegan',
            field=models.BooleanField(default=False, verbose_name='Вегетарианская'),
        ),
    ]
