# Generated by Django 3.2.7 on 2021-09-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_category_is_vegan'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='slug',
            field=models.SlugField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=256, null=True),
        ),
    ]
